export default function generateSnippet(
  userId: string,
  testId: string,
  testPageURL: string,
  conversionURL: string,
  selector: string,
  type: string,
  variations: any
) {
  const lines: string[] = [
    `<script defer>`,
    `"use strict";`,
    `(function () {`,
    'const _cookies = (document.cookie && document.cookie.split("; ")) || false;',
    `const _userId = "${userId}";`,
    `const _testId = "${testId}";`,
    `const _testPageURL = "${testPageURL}";`,
    `const _conversionURL = "${conversionURL}";`,
    `const _selector = "${selector}";`,
    `const _dom = document.querySelector(_selector);`,
    `const _type = "${type}";`,
    `const _variations = ${JSON.stringify(variations)};`,
    `function _getActiveVariationId() {`,
    `let activeVariationId =`,
    `(_cookies &&`,
    `_cookies`,
    `.find((row) => row.startsWith("testably_variation="))`,
    `?.split("=")[1]) ||`,
    `false;`,
    `if (!activeVariationId || !_variations[activeVariationId]) {`,
    `activeVariationId =`,
    `Object.keys(_variations)[`,
    `Math.floor(Math.random() * Object.keys(_variations).length)`,
    `].toString();`,
    `document.cookie = 'testably_variation=' + activeVariationId + ';max-age=2592000';`,
    `}`,
    `return activeVariationId;`,
    `}`,
    `const _activeVariationId = _getActiveVariationId();`,
    `const _url = window.location.href;`,
    `const _returningSession =`,
    `(_cookies &&`,
    `_cookies`,
    `.find((row) => row.startsWith("testably_visited="))`,
    `?.split("=")[1]) ||`,
    `false;`,
    `const _converted =`,
    `(_cookies &&`,
    `_cookies`,
    `.find((row) => row.startsWith("testably_converted="))`,
    `?.split("=")[1]) ||`,
    `false;`,
    `if (_url !== _testPageURL && _url !== _conversionURL) return;`,
    `if (_url === _testPageURL && !_returningSession) {`,
    `document.cookie = "testably_visited=true;max-age=2592000";`,
    `fetch("http://127.0.0.1:3333/api/v1/sessions", {`,
    `method: "post",`,
    `mode: "cors",`,
    `headers: {`,
    `"Content-Type": "application/json",`,
    `},`,
    `body: JSON.stringify({`,
    `userId: _userId,`,
    `testId: _testId,`,
    `variationId: _activeVariationId,`,
    `}),`,
    `});`,
    `}`,
    `if (_url === _testPageURL) {`,
    `switch (_type) {`,
    `case "copy":`,
    `{`,
    `_dom.textContent = _variations[_activeVariationId];`,
    `_dom.value = _variations[_activeVariationId];`,
    `}`,
    `break;`,
    `case "src":`,
    `{`,
    `_dom.src = _variations[_activeVariationId];`,
    `}`,
    `break;`,
    `case "visibility":`,
    `{`,
    `if (_variations[_activeVariationId] === "hidden")`,
    `_dom.style.display = "none";`,
    `}`,
    `break;`,
    `default:`,
    `break;`,
    `}`,
    `}`,
    `function _testablyConversion() {`,
    `if (_converted) return;`,
    `document.cookie = "testably_converted=true;max-age=2592000";`,
    `fetch("http://127.0.0.1:3333/api/v1/conversions", {`,
    `method: "post",`,
    `mode: "cors",`,
    `headers: {`,
    `"Content-Type": "application/json",`,
    `},`,
    `body: JSON.stringify({`,
    `userId: _userId,`,
    `testId: _testId,`,
    `variationId: _activeVariationId,`,
    `}),`,
    `});`,
    `}`,
    `if (_url === _conversionURL && _returningSession) {`,
    `_testablyConversion();`,
    `}`,
    `window.addEventListener("popstate", function (event) {`,
    `console.log("detected url change to:", window.location.href);`,
    `if (_url === _conversionURL && _returningSession) {`,
    `_testablyConversion;`,
    `}`,
    `});`,
    `})();`,
    `</script>`,
  ];
  return lines.join("");
}
